[build]
  publish = "."

# Optimisations de build
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = true

# HTTP2 Server Push pour les ressources critiques
[[headers]]
  for = "/index.html"
  [headers.values]
    Link = '''</tour.js>; rel=preload; as=script, </skin/fonts/CorporateABQ-Regular.woff2>; rel=preload; as=font; type=font/woff2; crossorigin, </skin/fonts/CorporateABQ-Bold.woff2>; rel=preload; as=font; type=font/woff2; crossorigin'''
    Cache-Control = "public, max-age=300"

# Redirection favicon
[[redirects]]
  from = "/favicon.ico"
  to = "/skin/rightLogo.png"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/panos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les assets skin (images, fonts, etc.)
[[headers]]
  for = "/skin/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pour tour.xml
[[headers]]
  for = "/tour.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600"
